# Generated by Django 4.0.3 on 2022-04-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discout',
            new_name='discount',
        ),
    ]
