# Generated by Django 4.0.3 on 2022-05-13 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_orders_is_delivered_product_likes_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
